[Mysql]
ConnectString = "root@tcp(localhost:3306)/mysql"

[Account]

Name = "admin"
Token = "admin"
Alias = "Jansora"

[Storage]
UseOss = true
EndPoint = "oss-cn-shanghai.aliyuncs.com"
AccessKeyId = "----"
AccessKeySecret = "----"
Bucket = "jansora"
# default domain is oss-cn-shanghai.aliyuncs.com
# if you want hidden the oss domain, use your domain instead. for example https://cdn.jansora.com
AliasDomain = "https://cdn.jansora.com"
OssPrefix = "Pancake/"

LocalSavePrefix = "/static/"
LocalReturnPrefix = "/static/"

