import type {Metadata} from "next";
import RootLayout from "@/components/layout/RootLayout";
import {auth} from "@/lib/auth/default";
import {SessionProvider} from "next-auth/react";
import React from "react";
import GlobalStoreProvider from "@/lib/store/global";
import {Session} from "next-auth";
import {GlobalStoreData} from "@/lib/declares/store";
import PageLayout from "@/components/layout/PageLayout";
import {MountBreadcrumb} from "@/hooks/use-breadcrumb";
import {BreadcrumbLink} from "@/components/ui/breadcrumb";
import {IconFont} from "@/components/ui/enhanced/IconFont";

export const metadata: Metadata = {
    title: "",
    description: "Generated by create next app",
};

export default async function Layout({children,}: Readonly<{ children: React.ReactNode; }>) {

    const session = await auth()

    return (

        <RootLayout>
            <SessionProvider session={session} basePath="/api/v1/auth">
                <GlobalStoreProvider initialData={initialData(session)}>
                    <MountBreadcrumb breadcrumb={{level: 1,
                        children:
                            <BreadcrumbLink href={"/"} >
                                <IconFont name="dashboard" className="mr-2 h-4 w-4 cursor-pointer "  />
                            </BreadcrumbLink>
                        ,
                        href: "/"
                    }}/>
                    <>
                        {children}
                    </>
                </GlobalStoreProvider>
            </SessionProvider>

        </RootLayout>

    );
}


const initialData = (session: Session | null): GlobalStoreData => {

    // @ts-ignore
    return {
        // @ts-ignore
        user: session?.user
    }
}

